package com.example.CampusLink.controller.Usuarios.Aluno;

import com.example.CampusLink.service.emailService;
import com.example.CampusLink.service.TwoFactorService;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.mock.web.MockHttpSession;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.verify;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.redirectedUrl;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.request;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@AutoConfigureMockMvc
@ActiveProfiles("test")
class CadastroAlunoIntegrationTest {

    private static final String EMAIL = "cadastro.aluno.fluxo@campuslink.invalid";
    private static final String RGM = "RGM001ABC01";
    private static final String SENHA = "SenhaForte123!";

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private TwoFactorService twoFactorService;

    @MockitoBean
    private emailService emailService;

    private MockHttpSession session;

    @BeforeEach
    void prepararBancoDeTeste() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS public."USUARIOS" (
                    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "nome" VARCHAR(100) NOT NULL,
                    "email" VARCHAR(100) NOT NULL,
                    "telefone" VARCHAR(30),
                    "datanasc" DATE,
                    "senha" VARCHAR(100) NOT NULL,
                    "perfil" VARCHAR(30),
                    "status" BOOLEAN
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS public."ALUNOS" (
                    "id_usuario" BIGINT PRIMARY KEY,
                    "rgm" VARCHAR(30),
                    CONSTRAINT "fk_aluno_usuario"
                        FOREIGN KEY ("id_usuario") REFERENCES public."USUARIOS"("id")
                )
                """);
        removerAlunoDoBanco();
    }

    @AfterEach
    void limparCenario() {
        removerAlunoDoBanco();
        if (session != null) {
            Object chaveCadastro = session.getAttribute("chave2FACadastro");
            if (chaveCadastro instanceof String chave) {
                twoFactorService.limparCodigo(chave);
            }
        }
    }

    @Test
    void cadastroComCodigoValido_devePersistirAlunoAposConfirmar2FA() throws Exception {
        MvcResult inicioCadastro = mockMvc.perform(post("/cadastrarAluno")
                        .with(csrf())
                        .param("rgm", RGM)
                        .param("nome", "Aluno de Integracao")
                        .param("email", EMAIL)
                        .param("telefone", "11999990002")
                        .param("dataNasc", "2001-04-05")
                        .param("senha", SENHA))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/verificarCadastro"))
                .andReturn();

        session = (MockHttpSession) inicioCadastro.getRequest().getSession(false);
        assertNotNull(session);

        ArgumentCaptor<String> codigoCaptor = ArgumentCaptor.forClass(String.class);
        verify(emailService).enviarCodigo(eq(EMAIL), codigoCaptor.capture());
        String codigo = codigoCaptor.getValue();
        assertTrue(codigo.matches("[0-9]{6}"));

        mockMvc.perform(post("/verificarCadastro")
                        .session(session)
                        .with(csrf())
                        .param("codigo", codigo))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/loginAluno"));

        Integer usuariosGravados = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM public.\"USUARIOS\" WHERE \"email\" = ?",
                Integer.class,
                EMAIL);
        Integer alunosGravados = jdbcTemplate.queryForObject("""
                SELECT COUNT(*)
                FROM public."ALUNOS" a
                JOIN public."USUARIOS" u ON u."id" = a."id_usuario"
                WHERE u."email" = ? AND a."rgm" = ?
                """,
                Integer.class,
                EMAIL,
                RGM);
        String senhaPersistida = jdbcTemplate.queryForObject(
                "SELECT \"senha\" FROM public.\"USUARIOS\" WHERE \"email\" = ?",
                String.class,
                EMAIL);

        assertEquals(1, usuariosGravados);
        assertEquals(1, alunosGravados);
        assertTrue(new BCryptPasswordEncoder(10).matches(SENHA, senhaPersistida));
        assertNull(session.getAttribute("cadastroPendente"));
    }

    private void removerAlunoDoBanco() {
        jdbcTemplate.update("""
                DELETE FROM public."ALUNOS"
                WHERE "id_usuario" IN (
                    SELECT "id" FROM public."USUARIOS" WHERE "email" = ?
                )
                """, EMAIL);
        jdbcTemplate.update("DELETE FROM public.\"USUARIOS\" WHERE \"email\" = ?", EMAIL);
    }
}
