package com.example.CampusLink.controller.Usuarios.Aluno;

import com.example.CampusLink.service.LoginAttemptService;
import com.example.CampusLink.service.TwoFactorService;
import com.example.CampusLink.service.emailService;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;

import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.ArgumentMatchers.matches;
import static org.mockito.Mockito.verify;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.redirectedUrl;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.request;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@AutoConfigureMockMvc
@ActiveProfiles("test")
class LoginAlunoIntegrationTest {

    private static final String EMAIL = "integracao.login.aluno@campuslink.invalid";
    private static final String SENHA = "SenhaForte123!";

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private LoginAttemptService loginAttemptService;

    @Autowired
    private TwoFactorService twoFactorService;

    @MockitoBean
    private emailService emailService;

    @BeforeEach
    void prepararBancoDeTeste() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS public."USUARIOS" (
                    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "nome" VARCHAR(100) NOT NULL,
                    "email" VARCHAR(100) NOT NULL,
                    "telefone" VARCHAR(30),
                    "datanasc" DATE,
                    "senha" VARCHAR(100) NOT NULL,
                    "perfil" VARCHAR(30),
                    "status" BOOLEAN
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS public."ALUNOS" (
                    "id_usuario" BIGINT PRIMARY KEY,
                    "rgm" VARCHAR(30),
                    CONSTRAINT "fk_aluno_usuario"
                        FOREIGN KEY ("id_usuario") REFERENCES public."USUARIOS"("id")
                )
                """);

        jdbcTemplate.update("""
                DELETE FROM public."ALUNOS"
                WHERE "id_usuario" IN (
                    SELECT "id" FROM public."USUARIOS" WHERE "email" = ?
                )
                """, EMAIL);
        jdbcTemplate.update("DELETE FROM public.\"USUARIOS\" WHERE \"email\" = ?", EMAIL);

        jdbcTemplate.update("""
                INSERT INTO public."USUARIOS"
                    ("nome", "email", "telefone", "datanasc", "senha", "perfil", "status")
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """,
                "Aluno de Integração",
                EMAIL,
                "11999990000",
                java.sql.Date.valueOf("2000-01-01"),
                new BCryptPasswordEncoder(10).encode(SENHA),
                "ALUNOS",
                true);

        Long idUsuario = jdbcTemplate.queryForObject(
                "SELECT \"id\" FROM public.\"USUARIOS\" WHERE \"email\" = ?",
                Long.class,
                EMAIL);
        jdbcTemplate.update(
                "INSERT INTO public.\"ALUNOS\" (\"id_usuario\", \"rgm\") VALUES (?, ?)",
                idUsuario,
                "RGM-INTEGRACAO-001");
    }

    @AfterEach
    void limparEstadoDoCenario() {
        jdbcTemplate.update("""
                DELETE FROM public."ALUNOS"
                WHERE "id_usuario" IN (
                    SELECT "id" FROM public."USUARIOS" WHERE "email" = ?
                )
                """, EMAIL);
        jdbcTemplate.update("DELETE FROM public.\"USUARIOS\" WHERE \"email\" = ?", EMAIL);
        twoFactorService.limparCodigo(EMAIL);
        loginAttemptService.loginSucesso(EMAIL);
    }

    @Test
    void postLoginAluno_deveConsultarBancoGerar2FAEIniciarSessaoDeVerificacao() throws Exception {
        mockMvc.perform(post("/loginAluno")
                        .with(csrf())
                        .param("email", EMAIL)
                        .param("senha", SENHA)
                        .param("confirmarSenha", SENHA))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/verificarAluno"))
                .andExpect(content().string(""))
                .andExpect(request().sessionAttribute("email2FA", EMAIL))
                .andExpect(request().sessionAttribute("redirect", "Login"))
                .andExpect(request().sessionAttribute("tipoUsuario", "aluno"))
                .andExpect(request().sessionAttributeDoesNotExist("usuarioLogado"));

        verify(emailService).enviarCodigo(eq(EMAIL), matches("[0-9]{6}"));
    }
}
