package com.example.CampusLink.dao;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.test.context.ActiveProfiles;

import java.sql.SQLException;

import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
@ActiveProfiles("test")
class UsuarioDaoPersistenceIntegrationTest {

    private static final String EMAIL_ENTRADA = " Cadastro.Integracao.Aluno@CampusLink.invalid ";
    private static final String EMAIL_NORMALIZADO = "cadastro.integracao.aluno@campuslink.invalid";
    private static final String RGM = "RGM-CADASTRO-INTEGRACAO-001";

    @Autowired
    private usuarioDAO usuarioDAO;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void prepararBancoDeTeste() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS public."USUARIOS" (
                    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "nome" VARCHAR(100) NOT NULL,
                    "email" VARCHAR(100) NOT NULL,
                    "telefone" VARCHAR(30),
                    "datanasc" DATE,
                    "senha" VARCHAR(100) NOT NULL,
                    "perfil" VARCHAR(30),
                    "status" BOOLEAN
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS public."ALUNOS" (
                    "id_usuario" BIGINT PRIMARY KEY,
                    "rgm" VARCHAR(30),
                    CONSTRAINT "fk_aluno_usuario"
                        FOREIGN KEY ("id_usuario") REFERENCES public."USUARIOS"("id")
                )
                """);

        removerDadosDoCenario();
    }

    @AfterEach
    void limparBancoDeTeste() {
        removerDadosDoCenario();
    }

    @Test
    void cadastrarAluno_devePersistirUsuarioVinculoEPermitirConsultarSenha() throws SQLException {
        String senhaHash = new BCryptPasswordEncoder(10).encode("SenhaForte123!");
        usuarioDAO.InsertCadastroUsuarioIntoBD(
                "Aluno",
                RGM,
                "Aluno de Teste",
                EMAIL_ENTRADA,
                "11999990001",
                "2000-03-04",
                senhaHash);

        Integer usuariosGravados = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM public.\"USUARIOS\" WHERE \"email\" = ?",
                Integer.class,
                EMAIL_NORMALIZADO);
        Integer alunosVinculados = jdbcTemplate.queryForObject("""
                SELECT COUNT(*)
                FROM public."ALUNOS" a
                JOIN public."USUARIOS" u ON u."id" = a."id_usuario"
                WHERE u."email" = ? AND a."rgm" = ?
                """,
                Integer.class,
                EMAIL_NORMALIZADO,
                RGM);
        String senhaConsultada = usuarioDAO.QueryLoginUsuario("Aluno", EMAIL_ENTRADA);

        assertEquals(1, usuariosGravados);
        assertEquals(1, alunosVinculados);
        assertEquals(senhaHash, senhaConsultada);
    }

    private void removerDadosDoCenario() {
        jdbcTemplate.update("""
                DELETE FROM public."ALUNOS"
                WHERE "id_usuario" IN (
                    SELECT "id" FROM public."USUARIOS" WHERE LOWER("email") = ?
                )
                """, EMAIL_NORMALIZADO);
        jdbcTemplate.update(
                "DELETE FROM public.\"USUARIOS\" WHERE LOWER(\"email\") = ?",
                EMAIL_NORMALIZADO);
    }
}
